remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
title: Callahan Culinary Creations
minima:
  skin: auto
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "recipe"